SBL.eLegistrator.HouseController.Web/Areas/Admin/Controllers/DashboardController.cs
using SBL.DomainModel.ComplexModel.MediaComplexModel;
using SBL.eLegistrator.HouseController.Filters;
using SBL.eLegistrator.HouseController.Web.Filters;
using SBL.eLegistrator.HouseController.Web.Helpers;
using SBL.eLegistrator.HouseController.Web.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SBL.eLegistrator.HouseController.Web.Areas.Admin.Controllers
{
    [Audit]
    [NoCache]
    [SBLAuthorize(Allow = "Authenticated")]
    public class DashboardController : Controller
    {
        //
        // GET: /Admin/Dashboard/

        public ActionResult Index()
        {
            MediaModel Mpass = new MediaModel();


            if (string.IsNullOrEmpty(CurrentSession.AssemblyId) && string.IsNullOrEmpty(CurrentSession.SessionId))
            {
                var model1 = (MediaModel)Helper.ExecuteService("Media", "GetDashBoardValue", Mpass);
                CurrentSession.AssemblyId = model1.AssemblyId.ToString();
                CurrentSession.SessionId = model1.SessionId.ToString();

            }

            return View();
        }

    }
}

SBL.eLegistrator.HouseController.Web/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Admin Dashboard";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
}
@Html.Partial("_LeftMenu")
<div class="main-content">  
    <div id="breadcrumbs" class="breadcrumbs">
        <script type="text/javascript">
            try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>


        </ul>
       
        <div class="legAssm">
          @*  <span class="label label-large label-pink arrowed-in-right arrowed">@Html.Raw(ViewBag.CurrentAssemblyName)</span>
            <span class="label label-large label-purple arrowed">@Html.Raw(ViewBag.CurrentSessionName)</span>*@
        </div>      

    </div>
 
   
    <div class="page-content">
       
    </div>
  

    <div class="footer">
        <div class="footer-inner">        
            <div class="footer-content">
                <span class="bigger-100">
                    <span class="blue bolder">eVidhan</span>
                    &nbsp;&nbsp;Application &copy; 2013-2014
                </span>
            </div>

        </div>
    </div>

    <a class="btn-scroll-up btn btn-sm btn-inverse" id="btn-scroll-up" href="#">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div>