SBL.eLegistrator.HouseController.Web/Areas/SuperAdmin/Models/MobileVersionsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Models
{
    public class MobileVersionsViewModel
    {
        public Int64 SlNo { get; set; }

        public string Code { get; set; }

        public int Major { get; set; }

        public int Minor { get; set; }

        public Int64 Build { get; set; }

        public string FilePath { get; set; }

        public string VersionDate { get; set; }

        public string DownloadPath { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? CreatedWhen { get; set; }

        public string ModifiedBy { get; set; }

        public DateTime? ModifiedWhen { get; set; }

        public string Mode { get; set; }

        public SelectList CodeList { get; set; }
    }
}

SBL.eLegistrator.HouseController.Web/Areas/SuperAdmin/Controllers/MobileVersionsController.cs
using SBL.DomainModel.Models.Mobiles;
using SBL.eLegistrator.HouseController.Web.Helpers;
using SBL.eLegistrator.HouseController.Web.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Extensions;
using SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Models;
using SBL.eLegistrator.HouseController.Filters;
using SBL.eLegistrator.HouseController.Web.Filters;
using System.IO;
using Microsoft.Security.Application;

namespace SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Controllers
{
    [Audit]
    [SBLAuthorize(Allow = "Authenticated")]
    [NoCache]
    public class MobileVersionsController : Controller
    {
        //
        // GET: /SuperAdmin/MobileVersions/

        public ActionResult Index()
        {

            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });

                }
                var mobiApps = (List<tMobileVersions>)Helper.ExecuteService("Mobiles", "GetAllMobileVersions", null);
                var model = mobiApps.ToViewModel();
                return View(model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a Error While Getting Mobile Version Details";
                return View("AdminErrorPage");
                throw ex;
            }
        }

        public ActionResult CreateMobiVersions()
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                var AppCodes = (List<mMobileApps>)Helper.ExecuteService("Mobiles", "GetAllAppCodes", null);
                var model = new MobileVersionsViewModel()
                {
                    Mode = "Add",
                    CodeList = new SelectList(AppCodes, "Code", "Code")

                };
                return View("CreateMobiVersions", model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a Error While Creating Mobile Versions Details";
                return View("AdminErrorPage");
                throw ex;
            }
        }

        [HttpPost]
        public JsonResult SaveMobileVersions(HttpPostedFileBase file)
        {
            try
            {
                MobileVersionsViewModel model = new MobileVersionsViewModel();

                model.Code = Request.Form["Code"].ToString();

                model.Major = Convert.ToInt32(Request.Form["Major"].ToString());

                model.Minor = Convert.ToInt32(Request.Form["Minor"].ToString());

                model.Build = Convert.ToInt32(Request.Form["Build"].ToString());

                model.VersionDate = Request.Form["VersionDate"].ToString();

                model.FilePath = Request.Form["FilePath"].ToString();

                model.Mode = Request.Form["Mode"].ToString();

                model.SlNo = Convert.ToInt32(Request.Form["SlNo"].ToString());

                string pdfPath = string.Empty;

                if (file != null)
                {
                    UploadFile(file, file.FileName, model.Code, out pdfPath);

                    model.FilePath = pdfPath.Replace(@"\", @"/");
                }

                var mobileVersions = model.ToDomainModel();

                if (model.Mode == "Add")
                {
                    Helper.ExecuteService("Mobiles", "CreateMobileVersions", mobileVersions);
                }
                else
                {
                    Helper.ExecuteService("Mobiles", "UpdateMobileVersions", mobileVersions);
                }

                return Json("Success", JsonRequestBehavior.AllowGet);
            }
#pragma warning disable CS0168 // The variable 'ex' is declared but never used
            catch (Exception ex)
#pragma warning restore CS0168 // The variable 'ex' is declared but never used
            {
                return Json("Failed", JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EditMobileVersions(int Id)
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                var AppCodes = (List<mMobileApps>)Helper.ExecuteService("Mobiles", "GetAllAppCodes", null);
                tMobileVersions verToEdit = (tMobileVersions)Helper.ExecuteService("Mobiles", "GetMobileVersionsBasedOnId", new tMobileVersions { SlNo = Id });
                var model = verToEdit.ToViewModel1(AppCodes, "Edit");
                var FileSettings = (SBL.DomainModel.Models.SiteSetting.SiteSettings)Helper.ExecuteService("SiteSetting", "GetFileAcessSettingLocal", null);
                model.DownloadPath = FileSettings.SettingValue + @"/" + verToEdit.FilePath;
                return View("CreateMobiVersions", model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a Error While Editing Mobile Versions Details";
                return View("AdminErrorPage");
                throw ex;
            }


        }

        public ActionResult DeleteMobileVersions(int Id)
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                tMobileVersions appsToRemove = (tMobileVersions)Helper.ExecuteService("Mobiles", "GetMobileVersionsBasedOnId", new tMobileVersions { SlNo = Id });
                Helper.ExecuteService("Mobiles", "DeleteMobileVersions", appsToRemove);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a Error While Deleting Mobile Apps Details";
                return View("AdminErrorPage");
                throw ex;
            }


        }

        private void UploadFile(HttpPostedFileBase File, string FileName, string code, out string dbFileName)
        {
            try
            {
                string savedFileName = string.Empty;

                dbFileName = string.Empty;

                if (File != null)
                {
                    var fileSettings = (SBL.DomainModel.Models.SiteSetting.SiteSettings)Helper.ExecuteService("SiteSetting", "GetDISFileSetting", null);

                    string dirPath = string.Empty;

                    //string fileNameWithoutExt = Path.GetFileNameWithoutExtension(File.FileName).Replace(".", "_").Replace("-", "_");

                    //string fileName = GetTimestamp(DateTime.Now) + "_" + fileNameWithoutExt + Path.GetExtension(File.FileName);

                    if (code == "PUB")
                    {
                        dirPath = Path.Combine(fileSettings.SettingValue + @"evapk\hpvspublic");

                        savedFileName = "Publicapp.apk";

                        dbFileName = "PUB" + @"\" + FileName;
                    }
                    else if (code == "MED")
                    {
                        dirPath = Path.Combine(fileSettings.SettingValue + @"evapk\hpvsmedia");

                        savedFileName = "hpvsmediaapp.apk";

                        dbFileName = "MED" + @"\" + FileName;
                    }
                    else if (code == "MEM")
                    {
                        dirPath = Path.Combine(fileSettings.SettingValue + @"evapk\hpvsmember");

                        savedFileName = "hpvsmemberapp.apk";

                        dbFileName = "GMEM" + @"\" + FileName;
                    }
                    else if (code == "GENCON")
                    {
                        dirPath = Path.Combine(fileSettings.SettingValue + @"evapk\hpvsconstituency");

                        savedFileName = "hpvsconstituency.apk";

                        dbFileName = "GENCON" + @"\" + FileName;
                    }
                    if (!Directory.Exists(dirPath))
                    {
                        Directory.CreateDirectory(dirPath);
                    }

                    rename(dirPath, savedFileName);
                    dirPath = dirPath + @"\" + savedFileName;

                   
                    File.SaveAs(dirPath);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        public void rename(string path, string savedFileName )
        {
            string oldFileName = savedFileName.Split('.')[0] +"_"+ DateTime.Now.ToString("dd_MM_yyyy") + ".apk";
            if (System.IO.File.Exists(Path.Combine(path, oldFileName)) == true)
            {
                System.IO.File.Delete(Path.Combine(path, oldFileName));
            }
            
            if (System.IO.File.Exists(Path.Combine(path, savedFileName)))
            {
                System.IO.File.Move(Path.Combine(path, savedFileName), Path.Combine(path, oldFileName));
            }
           
        }
        public ActionResult Download(string filePathWithName, string code)
        {
            filePathWithName = Sanitizer.GetSafeHtmlFragment(filePathWithName);
            string filename = string.Empty;
            if (code == "PUB")
            {
                filename = @"C:\inetpub\e_Vidhan\FileStructure\evapk\hpvsconstituency\" + System.IO.Path.GetFileName(filePathWithName);
            }
            else if (code == "MEM")
            {
                filename = @"C:\inetpub\e_Vidhan\FileStructure\evapk\hpvsmember\" + System.IO.Path.GetFileName(filePathWithName);

SBL.eLegistrator.HouseController.Web/Areas/SuperAdmin/Views/MobileVersions/Index.cshtml
@model  IEnumerable<SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Models.MobileVersionsViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
    int count = 0;
}



@Html.Action("LeftNavigationMenu", "SuperAdmin")
<div class="main-content">
    @Html.Partial("_BreadcrumbsPartial")
    <!-- #section:basics/content.breadcrumbs -->
    <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
            try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="@Url.Action("Index", "MobileVersions")">@Resources.MasterDataDashboard.Home</a>
            </li>

            <li>
                <a href="@Url.Action("Index", "MobileVersions")">Mobile Versions</a>
            </li>
            <li class="active">@Resources.MasterDataDashboard.List</li>
        </ul>

        @* <div class="legAssm">
            <span class="label label-large label-pink arrowed-in-right arrowed">@Html.Raw(ViewBag.CurrentAssemblyName)</span>
            <span class="label label-large label-purple arrowed">@Html.Raw(ViewBag.CurrentSessionName)</span>
        </div>*@

    </div>

    <!-- /section:basics/content.breadcrumbs -->
    <div class="page-content">
        <!-- #section:settings.box -->


        <!-- /section:settings.box -->
        <div class="ace-settings-container" id="ace-settings-container" style="margin-right: 20px;">
            <button class="btn  btn-sm btn-info" onclick="javascript:window.location.href=' /SuperAdmin/MobileVersions/CreateMobiVersions';">
                <i class="ace-icon fa fa-pencil-square-o bigger-150"></i>
                <span class="bigger-110">@Resources.MasterDataDashboard.New</span>
            </button>
        </div>
        <div class="page-header">
            <h1>Mobile Versions
                <small>
                    <i class="ace-icon fa fa-angle-double-right"></i>
                    Mobile Versions List
                </small>
            </h1>
        </div>
        <div id="Menu">
            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="pass-table">


                        @if (Model != null)
                        {
                            if (Model.Count() > 0)
                            {       
                                
                          
                            <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-2" aria-describedby="sample-table-2_info">
                                <thead>
                                    <tr role="row">

                                        <th class="center sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="" onclick="javascript:window.location.href=' /SuperAdmin/MobileVersions/Index';">SNo</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Code</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Major</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Minor</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Build</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Date Of Mobile Version</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending"></th>

                                    </tr>
                                </thead>
                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                    @foreach (var item in Model)
                                    {
                                        count = count + 1;  
                                        <tr>
                                            <td class="center" style="width: 10%">
                                                @count
                                            </td>
                                            <td style="width: 20%">@item.Code</td>
                                            <td style="width: 10%">@item.Major</td>
                                            <td style="width: 10%">@item.Minor</td>
                                            <td style="width: 20%">@item.Build</td>
                                            <td style="width: 20%">@Convert.ToDateTime(item.VersionDate).ToString("dd/MM/yyyy")</td>
                                            <td class="center" style="width: 10%">
                                                <div class="hidden-sm hidden-xs action-buttons">

                                                    <a data-rel="tooltip" class="green tooltip-success" title="Edit"  href="@Url.Action("EditMobileVersions", "MobileVersions", new { Id = item.SlNo })">
                                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                    </a>
                                                    <a data-rel="tooltip" class="red tooltip-error" title="Delete" id="DeleteLink"  href="@Url.Action("DeleteMobileVersions", "MobileVersions", new { Id = item.SlNo })">
                                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                    </a>
                                                </div>

                                                <div class="hidden-md hidden-lg">
                                                    <div class="inline position-relative">
                                                        <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                                            <i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
                                                        </button>

                                                        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">

                                                            <li>
                                                                <a  href="@Url.Action("EditMobileVersions", "MobileVersions", new { Id = item.SlNo })" class="tooltip-success" data-rel="tooltip" title="Edit">
                                                                    <span class="green">
                                                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                                    </span>
                                                                </a>

                                                            </li>

                                                            <li>
                                                                <a  href="@Url.Action("DeleteMobileVersions", "MobileVersions", new { Id = item.SlNo })"  class="tooltip-error" data-rel="tooltip" title="Delete">
                                                                    <span class="red">
                                                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                                    </span>
                                                                </a>

                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>                                                                
                                    }

                                </tbody>
                            </table>
                            <!-- PAGE CONTENT ENDS -->
                            }
                            else
                            {
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="alert alert-info">

                                        <strong>No Records Found..!</strong><br />
                                    </div>
                                </div>
                            </div>
                            }
                        }

                    </div>

                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
        </div>
        <!-- /.page-content -->
    </div>
    <!-- /.main-content -->

    <div class="footer">
        <div class="footer-inner">
            <!-- #section:basics/footer -->
            <div class="footer-content">
            </div>

            <!-- /section:basics/footer -->
        </div>
    </div>

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div>

<div id="dialog-confirm" class="hide">
    <div id="DialogMessage" class="alert alert-info bigger-110">
        Are You Sure Want to Delete.
    </div>

    <div class="space-6"></div>
</div>
<div id="divDataContainer">
</div>

<script src="/assets/js/jquery.dataTables.min.js"></script>
<script src="/assets/js/jquery.dataTables.bootstrap.js"></script>
<script src="~/assets/js/bootbox.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $("#mobiles").addClass("active open");
        $("#mobilesSub").addClass("nav-show").css("display", "block");
        $("#mbVersionslist").addClass("active");
        $("#mobilelinkid").removeClass("fa-comment").addClass("fa-comment-o");
    });

    jQuery(function ($) {
        var oTable1 =
        $('#sample-table-2')
        //.wrap("<div class='dataTables_borderWrap' />")   //if you are applying horizontal scrolling (sScrollX)
        .dataTable({
            bAutoWidth: true,
            "aoColumns": [
              { "bSortable": false },
              null, null, null, null, null,
              { "bSortable": false }
            ]

        });

        $('[data-rel="tooltip"]').tooltip({ placement: tooltip_placement });
        function tooltip_placement(context, source) {
            var $source = $(source);
            var $parent = $source.closest('table')
            var off1 = $parent.offset();
            var w1 = $parent.width();

            var off2 = $source.offset();
            //var w2 = $source.width();

            if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2)) return 'right';
            return 'left';
        }

    })


    $(" #DeleteLink").on('click', function (e) {
        e.preventDefault();
        var url = $(this).attr('href');
        var message = "";
        var buttonlabel = "";
        var buttoncss = "";
        var title = "";
        if ($(this).attr('id') == "DeleteLink") {

            message = '@Resources.MasterDataDashboard.Areyousurewanttodelete';
            buttonlabel = '@Resources.MasterDataDashboard.Delete';
            buttoncss = "btn-danger";
            title = '@Resources.MasterDataDashboard.DeleteConfirmation'
        }

        bootbox.dialog({
            message: message,
            title: title,
            buttons: {
                success: {
                    label: buttonlabel,
                    className: buttoncss,
                    callback: function () {
                        window.location.href = url;
                    }
                },
                danger: {
                    label: '@Resources.MasterDataDashboard.Cancel',
                    className: "btn",
                    callback: function () {
                        $('.modal-dialog').modal('hide');
                    }
                },

            }
        });
    });

</script>