SBL.eLegistrator.HouseController.Web/Areas/Accounts/Models/designationList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SBL.eLegistrator.HouseController.Web.Areas.Accounts.Models
{
    public class designationList
    {
        public string designationName { get; set; }
        public int? designationID { get; set; }
    }

}

SBL.eLegistrator.HouseController.Web/Areas/PISModule/Controllers/PISDesignationController.cs
using SBL.DomainModel.Models.Department;
using SBL.DomainModel.Models.Grievance;
using SBL.DomainModel.Models.PISMolues;
using SBL.DomainModel.Models.UserModule;
using SBL.eLegislator.HPMS.ServiceAdaptor;
using SBL.eLegistrator.HouseController.Web.Helpers;
using SBL.eLegistrator.HouseController.Web.Areas.PISModule.Models;
using SBL.eLegistrator.HouseController.Web.Utility;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SBL.DomainModel.Models.User;
using SBL.DomainModel.Models.Office;
using SBL.DomainModel.Models.PISModules;
using System.IO;

namespace SBL.eLegistrator.HouseController.Web.Areas.PISModule.Controllers
{
    public class PISDesignationController : Controller
    {
        //
        // GET: /PISModule/PISDesignation/

        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult DesignationIndex(int pageId = 1, int pageSize = 20)
        {
            try
            {
               tPISEmpSanctionpost smodel = new tPISEmpSanctionpost();
                if (!string.IsNullOrEmpty(CurrentSession.DeptID as string))
                {
                    smodel.Deptid=CurrentSession.DeptID as string;
                    if(CurrentSession.OfficeId !=""  || CurrentSession.OfficeId !=null)
                    {
                    smodel.POfficeId = Convert.ToInt32(CurrentSession.OfficeId);
                    }
                }
                if (CurrentSession.SubDivisionId != null)
                {
                  smodel.SubId = CurrentSession.SubDivisionId;
                }
                var DesignationList = (List<tPISEmpSanctionpost>)Helper.ExecuteService("PISModule", "GetAllSenctionPost", smodel);

                ViewBag.PageSize = pageSize;
                List<tPISEmpSanctionpost> pagedRecord = new List<tPISEmpSanctionpost>();
                if (pageId == 1)
                {
                    pagedRecord = DesignationList.Take(pageSize).ToList();
                }
                else
                {
                    int r = (pageId - 1) * pageSize;
                    pagedRecord = DesignationList.Skip(r).Take(pageSize).ToList();
                }

                ViewBag.CurrentPage = pageId;
                ViewData["PagedList"] = Helper.BindPager(DesignationList.Count, pageId, pageSize);


                if (TempData["Msg"] != null)
                    ViewBag.Msg = TempData["Msg"].ToString();
                if (TempData["Class"] != null)
                    ViewBag.Class = TempData["Class"].ToString();
                if (TempData["Notification"] != null)
                    ViewBag.Notification = TempData["Notification"].ToString();

                ViewBag.DesignationCount = DesignationList.Count;
                smodel.PostList = pagedRecord;
                if (!string.IsNullOrEmpty(CurrentSession.AadharId as string) && !string.IsNullOrEmpty(CurrentSession.DeptID as string))
                {
                    tPISEmployeePersonal offMdl = new tPISEmployeePersonal();
                    offMdl.AadharID = CurrentSession.AadharId;
                    offMdl.deptid = CurrentSession.DeptID;
                    offMdl.POfficeId = Convert.ToInt32(CurrentSession.OfficeId);
                    smodel.OfficeList = (List<mOffice>)Helper.ExecuteService("Department", "GetOfficeByAadharId", offMdl);
                  
                }
                return PartialView("/Areas/PISModule/Views/PISDesignation/_DesignationIndex.cshtml", smodel);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Their is a Error While Getting Designation List";
                return PartialView("/Areas/SuperAdmin/Views/Shared/AdminErrorPage.cshtml");
                throw ex;
            }
        }
        public ActionResult CheckUserExistToPost(string id)
        {
            try
            {
                tPISEmpSanctionpost smodel = new tPISEmpSanctionpost();
                smodel.Id = Convert.ToInt32(id);
                bool chk = (bool)Helper.ExecuteService("PISModule", "CheckEmpExist", smodel);

                return Json(chk, JsonRequestBehavior.AllowGet);
              
            }
            catch (Exception)
            {
                ViewBag.Msg = "Ooops....! any error occured.";
                ViewBag.Class = "alert alert-error";
                ViewBag.Notification = "Error";
                throw;
            }
        }
        public PartialViewResult DeleteSantion(string id, int pageId = 1, int pageSize = 20)
        {
            try
            {
                
                tPISEmpSanctionpost smodel = new tPISEmpSanctionpost();
                smodel.Id = Convert.ToInt32(id);
                List<tPISEmpSanctionpost> pagedRecord = new List<tPISEmpSanctionpost>();
           
                  Helper.ExecuteService("PISModule", "DeleteSantion", smodel);
                  if (!string.IsNullOrEmpty(CurrentSession.DeptID as string))
                  {
                      smodel.Deptid = CurrentSession.DeptID as string;
                  }
                  var DesignationList = (List<tPISEmpSanctionpost>)Helper.ExecuteService("PISModule", "GetAllSenctionPost", smodel);

                  ViewBag.PageSize = pageSize;
                 
                  if (pageId == 1)
                  {
                      pagedRecord = DesignationList.Take(pageSize).ToList();
                  }
                  else
                  {
                      int r = (pageId - 1) * pageSize;
                      pagedRecord = DesignationList.Skip(r).Take(pageSize).ToList();
                  }

                  ViewBag.CurrentPage = pageId;
                  ViewData["PagedList"] = Helper.BindPager(DesignationList.Count, pageId, pageSize);

                  ViewBag.Msg = "Sucessfully deleted";
                  ViewBag.Class = "alert alert-info";
                  ViewBag.Notification = "Success";


                  ViewBag.DesignationCount = DesignationList.Count;
                  smodel.PostList = pagedRecord;
                  if (!string.IsNullOrEmpty(CurrentSession.AadharId as string) && !string.IsNullOrEmpty(CurrentSession.DeptID as string))
                  {
                      tPISEmployeePersonal offMdl = new tPISEmployeePersonal();
                      offMdl.AadharID = CurrentSession.AadharId;
                      offMdl.deptid = CurrentSession.DeptID;
                      if (!string.IsNullOrEmpty(CurrentSession.OfficeId as string))
                      {
                          offMdl.POfficeId = Convert.ToInt32(CurrentSession.OfficeId);
                      }
                      smodel.OfficeList = (List<mOffice>)Helper.ExecuteService("Department", "GetOfficeByAadharId", offMdl);

                  }

                  return PartialView("/Areas/PISModule/Views/PISDesignation/_DesignationList.cshtml", smodel);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Their is a Error While Getting Designation List";
                return PartialView("/Areas/SuperAdmin/Views/Shared/AdminErrorPage.cshtml");
                throw ex;
            }
        }
        public PartialViewResult AddSantionpostForm(string did, string type)
        {
            try
            {
                PISCustom model = new PISCustom();
                if (type == "update")
                {
                    tPISEmpSanctionpost smodel = new tPISEmpSanctionpost();
                    smodel.Id = Convert.ToInt32(did);
                    smodel = (tPISEmpSanctionpost)Helper.ExecuteService("PISModule", "GetSantionpostByid", smodel);
                    model.DeptId = smodel.Deptid;
                    model.OfficeId = smodel.POfficeId;
                    model.Id = smodel.Id;
                    model.type = type;
                    ViewBag.departmentid = smodel.Deptid;
                    ViewBag.OfficeID = smodel.POfficeId;
                    ViewBag.type = type;
                    model.PDesignationId = smodel.PDesignationId;
                    model.AllDesignationIds = smodel.PDesignationId.ToString().Split(',').ToList();
                    model.DepartmentName = smodel.DepartmentName;
                    model.Priority = smodel.Priority;
                    //model.AllDesignationIds = smodel.desigcd.ToString();
                }
                if (!string.IsNullOrEmpty(CurrentSession.AadharId as string) && !string.IsNullOrEmpty(CurrentSession.DeptID as string))
                {
                    model.DeptId = CurrentSession.DeptID;
                    tPISEmployeePersonal offMdl = new tPISEmployeePersonal();
                    offMdl.AadharID = CurrentSession.AadharId;
                    offMdl.deptid = CurrentSession.DeptID;
                    if (!string.IsNullOrEmpty(CurrentSession.OfficeId as string))
                    {
                        offMdl.POfficeId = Convert.ToInt32(CurrentSession.OfficeId);
                    }
                    model.OfficeList = (List<mOffice>)Helper.ExecuteService("Department", "GetOfficeByAadharId", offMdl);
                    string Departmentid = offMdl.deptid;
                    model.DesignationList = (List<mPISDesignation>)Helper.ExecuteService("PISModule", "GetAllDesignationByDeptId", Departmentid);

                }
                return PartialView("/Areas/PISModule/Views/PISDesignation/_AddSantionpostForm.cshtml", model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Their is a Error While Getting Designation List";
                return PartialView("/Areas/SuperAdmin/Views/Shared/AdminErrorPage.cshtml");
                throw ex;
            }
        }
        public ActionResult OfficeDrpList()
        {

            tPISEmployeePersonal newModel = new tPISEmployeePersonal();

SBL.eLegistrator.HouseController.Web/Areas/PISModule/Views/PISDesignation/AddSanFillPostForm.cshtml
@model SBL.DomainModel.Models.PISMolues.tPISEmpSanctionpost


<style>
    .ErrorMessage {
        color: red;
        font-weight: bold;
        padding-left: 5px;
        padding-top: 15px;
    }

    .ms-choice {
        width: 311px;
    }

    .footer .footer-inner .footer-content {
        bottom: 0px;
    }
</style>

@*<script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>*@

@*<form method="post" enctype="multipart/form-data" action="/PISDesignation/SaveSanFillPost" id="SaveSantionPostForm">*@

    <div class="widget-body">
        <div class="widget-main no-padding-right no-padding-left">
            <div class="profile-user-info profile-user-info-striped">

                <div class="profile-info-row">
                </div>
                @using (Html.BeginForm("SaveSanFillPost", "PISDesignation", FormMethod.Post, new { id = "SaveSantionPostForm", enctype = "multipart/form-data", @class = "form-horizontal", @role = "form" }))
            {
                     @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.Id)
                      @Html.HiddenFor(m => m.Mode)
                    <div class="profile-info-row">
                    <div class="profile-info-name">Office :</div>
                    <div class="profile-info-value">
                        @Html.DropDownListFor(m => m.POfficeId, new SelectList(Model.OfficeList, "OfficeId", "officename"), "-- Select Office ( Filter ) --", new { @class = "col-xs-10 col-sm-10", @tabindex = "2", @id = "ddloffice", @style = "width:86.3333%;" })
                        <div class="input-group col-xs-12">
                        </div>
                        <div class="help-block col-xs-12 col-sm-reset inline">
                            @*@Html.ValidationMessageFor(model => model.POfficeId)*@
                        </div>
                    </div>
                </div>
                <div class="profile-info-row">
                    <div class="profile-info-name">Description :</div>
                    <div class="profile-info-value">
                          @Html.TextBoxFor(t => t.Description, new { style = "width:62.3333%;" })
                        @*@Html.ListBoxFor(m => m.AllDesignationIds, new SelectList(Model.DesignationList, "Id", "designame", "0"), new { @id = "ddldesignation", @tabindex = "1", @class = "form-control", @multiple = "multiple", style = "width: 463px", @onchange = "get();" })*@
                        @*@Html.DropDownListFor(m => m.PDesignationId, new SelectList(Model.DesignationList, "Id", "designame"), "-Select-", new { @id = "PDesignationId", @name = "PDesignationId", @style = "display:none;width: 323px" })*@

                        <div class="input-group col-xs-12">
                        </div>
                        <div class="help-block col-xs-12 col-sm-reset inline">
                            @*@Html.ValidationMessageFor(model => model.DesignationList)*@
                        </div>
                    </div>
                </div>
                if (Model.Mode == "Create")
                {

                }
                else
                { 
                  <div class="profile-info-row">
                    <div class="profile-info-name">Last Modified On :</div>
                    <div class="profile-info-value">
                          @Html.TextBoxFor(t => t.ModifiedDate, new {@readonly = true, style = "width:62.3333%;"})
                        @*@Html.ListBoxFor(m => m.AllDesignationIds, new SelectList(Model.DesignationList, "Id", "designame", "0"), new { @id = "ddldesignation", @tabindex = "1", @class = "form-control", @multiple = "multiple", style = "width: 463px", @onchange = "get();" })*@
                        @*@Html.DropDownListFor(m => m.PDesignationId, new SelectList(Model.DesignationList, "Id", "designame"), "-Select-", new { @id = "PDesignationId", @name = "PDesignationId", @style = "display:none;width: 323px" })*@

                        <div class="input-group col-xs-12">
                        </div>
                        <div class="help-block col-xs-12 col-sm-reset inline">
                            @*@Html.ValidationMessageFor(model => model.DesignationList)*@
                        </div>
                    </div>
                </div>
                }
                  

                      <div class="profile-info-row">
                    <div class="profile-info-name">Attachment :</div>
                    <div class="profile-info-value" style="/* padding: 19px; */padding-top: 13px;">
                          <div >
                            @*   <input style="padding-top: 24px" type="file" id="file1" name="file1" accept="application/pdf" />*@

                                       <input type="file" id="Image" style="padding:0" name="file" />
                                        @*<input type="file" id="file" style="padding:0" name="file" />*@
                                        <div class="help-block col-xs-12 col-sm-reset inline">
                                            <span class="field-validation-error" id="filevalidation"></span>
                                        </div>

                                    </div>
                      
                        <div class="input-group col-xs-12">
                        </div>
                        <div class="help-block col-xs-12 col-sm-reset inline">
                            @*@Html.ValidationMessageFor(model => model.DesignationList)*@
                        </div>
                    </div>
                </div>
                                
                       
               
                    
                        <div class="wizard-actions">
            <div style="margin-bottom: 40px;">
                <div class="form-inline">
                @*    <button type="button" id="btnAddpost" onclick="AddSantionPost(this.value);" name="btnAddpost" class="btn btn-primary" value="Save">
                        <i class="ace-icon fa fa-floppy-o align-top bigger-140"></i>

                        <span>Save</span>
                    </button>*@
                @*    <button type="button" id="btnUpdatepost" onclick="AddSantionPost(this.value);" name="btnAddpost" class="btn btn-primary" value="Update">
                        <i class="ace-icon fa fa-floppy-o align-top bigger-140"></i>

                        <span>Update</span>
                    </button>*@

                     @if (Model.Mode == "Create")
                {
                                <button type="submit" id="savebtn" class="btn btn-sm btn-purple " onclick="AddSantionPost(this.value);">
                                        <i class="ace-icon fa fa-floppy-o bigger-125"></i>
                                        Save</button>
                }
                     else
                     {
                     <button type="submit" id="updatebtn" class="btn btn-sm btn-purple ">
                                        <i class="ace-icon fa fa-floppy-o bigger-125"></i>
                                        Update</button>
                     }


                    
                </div>
            </div>
        </div>
            }

            </div>
        </div>

    

    </div>
@*</form>*@

<link href="~/Content/MultiSelectList/multiple-select.css" rel="stylesheet" />

<script src="~/Scripts/MultiSelectBox/jquery.multiple.select.js"></script>
<script>
    $(document).ready(function () {

        $('.IsnumericClass').keypress(function (e) {
            var key = (e.which) ? e.which : e.keyCode;
            if ((key >= 48 && key <= 57) || (key == 44) || (key == 8)) {

                return true;
            }
            else {
                return false;
            }
        });
        // $("#leftdivsantion").css("width", "476px");


        //$("#ddldesignation").multipleSelect({ selectAll: true, placeHolder: "Select Designation" });
        $(".ms-choice").css("width", "328px");
        $(".ms-drop").css("width", "328px");

        if ('@ViewBag.OfficeID' != "") {

            getOfficebyDeptid();
            $("#btnAddpost").hide();
            $("#btnUpdatepost").show();
            $(".ms-choice").css("display", "none");
            $("#PDesignationId").show();
            $("#PriorityDiv").show();

        }
        else {
            $(".Member").removeAttr('checked');
            $("#btnmultichkbox").text('Select Multiple Designation');
            $("#btnAddpost").show();
            $("#btnUpdatepost").hide();
            $.ajax({
                url: "/PISModule/PISDesignation/OfficeDrpList",
                type: 'POST',
                data: {},
                success: function (data) {
                    $("#ddloffice").empty();
                    //$("#ddloffice").append("<option value=''>-- Select Office -- </option>");
                    $.each(data, function (index, optiondata) {
                        $("#ddloffice").append("<option value='" + optiondata.OfficeId + "'>" + optiondata.officename + "</option>");
                    });
                    $("#ddloffice").val(@SBL.eLegistrator.HouseController.Web.Utility.CurrentSession.OfficeId)
                    $('#ddloffice option:not(:selected)').attr('disabled', true);
                }

            })

        }


        //$("#DeptId").change(function () {
        //    var DepartmentID = $('#DeptId').val();
        //    if (DepartmentID == "") {
        //        ShowNotification("error", "Please Select Department From !!!.....");
        //    }
        //    else {
        //        $.ajax({
        //            url: "/PISModule/PISDesignation/OfficeDrpList",
        //            type: 'POST',
        //            data: { deptid: DepartmentID },
        //            success: function (data) {
        //                $("#OfficeId").empty();
        //                $("#OfficeId").append("<option value=''>-- Select Office -- </option>");
        //                $.each(data, function (index, optiondata) {
        //                    $("#OfficeId").append("<option value='" + optiondata.OfficeId + "'>" + optiondata.officename + "</option>");
        //                });
        //            }
        //        })
        //    }
        //});

    });
    function getOfficebyDeptid() {

        $.ajax({
            url: "/PISModule/PISDesignation/OfficeDrpList",
            type: 'POST',
            data: {},
            success: function (data) {

                $("#ddloffice").empty();
                //$("#ddloffice").append("<option value=''>-- Select Office -- </option>");
                $.each(data, function (index, optiondata) {
                    $("#ddloffice").append("<option value='" + optiondata.OfficeId + "'>" + optiondata.officename + "</option>");
                });
                if ('@ViewBag.OfficeID' != "") {

                    $("select[name='POfficeId'] option[value=" + '@ViewBag.OfficeID' + "]").prop("selected", "selected");
                    //   $("#ddloffice").val(@SBL.eLegistrator.HouseController.Web.Utility.CurrentSession.OfficeId)
                    $('#ddloffice option:not(:selected)').attr('disabled', true);
                }

            }

        })

    }
    function AddSantionPost(type) {

        //return false;
        var file = document.getElementById('file1').value;
        $('.ErrorMessage').remove('');
        $('.ErrorMessage').remove();
        $("br").remove();
        var IsValid = true;
        if ($('#ddloffice').val() == '') {
            $('#ddloffice').css("border", "1px solid red");
            $('#ddloffice').after("<br><br><span class='ErrorMessage'>Office Field  Required</span>");
            IsValid = false;
        }
        if (IsValid == true) {
            // alert('ss');
            var QData = $('#SaveSantionPostForm').serialize();
            var file = document.getElementById('file1');
           // alert(file);
            var id = $('#Id').val();
          //  var id = $('#Description').val();
            $.ajax({
                cache: false,
                async: true,
                type: "POST",
                url: '/PISModule/PISDesignation/SaveSanFillPost',
                data: QData,
                beforeSend: function () {
                    $('#loader-wrapper').show();
                },
                success: function (data) {
                  //  $('#MainDiv').empty();
                  //  $('#MainDiv').append(data);

                    $("#loader-wrapper").hide();

                }
            });
        }
    }
</script>

SBL.eLegistrator.HouseController.Web/Areas/PISModule/Views/PISDesignation/SanFillPostList.cshtml
@using SBL.eLegistrator.HouseController.Web.Areas.AccountsAdmin.Models
@model SBL.DomainModel.Models.PISMolues.tPISEmpSanctionpost

@{  int count = 0;
    if (ViewBag.CurrentPage > 1)
    {

        count = (ViewBag.PageSize * (ViewBag.CurrentPage - 1));
    }
}
<!-- PAGE CONTENT BEGINS -->
<script>
    $(document).ready(function () {
        $("#serialn").css("width", "100px");
    });

</script>
   <div class="pass-table">
    @if (Model != null)
    {
        if (Model.SancFillPostList.Count() > 0)
        {       
        <input type="hidden" id="pageId" name="pageId" value="@ViewBag.CurrentPage" />
        <div class="table-header">
            <div class="form-group">
                @if (ViewBag.Msg != null)
                {
                    <div class="@ViewBag.Class" id="MsgDiv">
                        <button type="button" class="close" data-dismiss="alert"><i class="ace-icon fa fa-times"></i></button>
                        <strong><i class="ace-icon fa fa-check-square-o"></i>@ViewBag.Notification ! </strong>@ViewBag.Msg
                    </div>
                }

            </div>
        </div>@*  
        <div>

            <label>Display</label>
            <select size="1" name="PageSize" id="PazeSize">
                 <option value="20" selected="selected">20</option>
                <option value="40">40</option>
                <option value="60">60</option>
                <option value="80">80</option>
                 <option value="100">100</option>
            </select>
            <label>Records</label>
        </div>           
        *@<table class="table  table-bordered  dataTable" id="tblSentiopostList" aria-describedby="sample-table-2_info">
            <thead>
                <tr role="row">
                    <th class="center sorting_disabled" role="columnheader"  id="serialn" rowspan="1" colspan="1" aria-label="">@Resources.MasterDataDashboard.SNo</th>
                    @*<th class="sorting SortingData" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Department</th>*@
                    <th class="sorting SortingData" style="text-align:center" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Description</th>
                    <th class="sorting" style="text-align:center" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Last Updated On</th>
                    @* <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Sanction Post</th>
                      <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Filled Post</th>*@
                   <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Pdf</th>
                   
                     <th class="sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="">Action</th>

                </tr>
            </thead>
            <tbody role="alert" aria-live="polite" aria-relevant="all">
                @foreach (var item in Model.SancFillPostList)
                {
                   //var count = count + 1; 
                  
                    <tr id="Row-">
                        <td class="center"  style="width: 10%">
                            1.
                        </td>
                     @*   <td class="center" style="width: 50%">


                            @item.DepartmentName
                        </td>*@
                        <td class="center" style="width: 40%">
                            @item.Description

                        </td>
                            <td class="center" style="width: 40%">
                            @item.ModifiedDate

                        </td>
                        <td class="center" style="width: 40%">
                            @if (!string.IsNullOrEmpty(item.PdfLocation))
                                        {

                                            var filepath = Model.FileAccessPath + item.PdfLocation; 
                                           <a href="@filepath" target="_blank">Attachment</a>
                                            
                                        }
                                        else
                                        {
                                           
                                        }
                            
                            
                            
                            
                             @if(item.PdfLocation!=null)
                            {
                            
                             <img src="~/Images/Common/PDF.png" width="25" height="25" /> 
                            }
                           
                        </td>
                        @*      @item.PdfLocation <td> @item.sanctpost</td>
                         <td> @item.Filledpost</td>*@

                     

                        <td class="center" style="width: 10%">


                            <div class="hidden-sm hidden-xs action-buttons">
                                <table>
                                    <tr>
                                        <td><a data-rel="tooltip" class="btn btn-minier btn-danger" title="Edit" onclick="OpenSactionForm('@item.Id','Update');" id="aedit"  href="#">Edit
                                        </a>
                                        </td>
                                        @*<td><a data-rel="tooltip" class="btn btn-minier btn-danger" title="Delete" onclick="DeleteSantion('@item.Id');" id="adelete"  href="#">Delete
                                        </a></td>*@
                                    </tr>
                                </table>


                            </div>

                        </td>
                    </tr>                                                                
                }

            </tbody>
        </table>
        <!-- PAGE CONTENT ENDS -->
        <!-- PAGER START -->
        <div>@{Html.RenderPartial("~/Areas/AccountsAdmin/Views/Shared/_Pager.cshtml");}</div>
        <!-- PAGER ENDS -->
        }
        else
        {
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-info">
                    <strong>No Records Found</strong><br />
                </div>
            </div>
        </div>
        }

    }
</div>

@*<script src="/assets/js/jquery.dataTables.min.js"></script>*@
<script src="/assets/js/jquery.dataTables.bootstrap.js"></script>

<!-- /.col -->
<script type="text/javascript">

    $(document).ready(function () {

    
        setTimeout(function () {
            $("#MsgDiv").slideUp(400);
        }, 2000);

        $("#PazeSize").val(@ViewBag.PageSize)

        $('#PazeSize').change(function () {
            var PageSize = $("#PazeSize").val();
            $.ajax({
                type: "POST",
                url: '/PISModule/PISDesignation/GetSanFillPostbyPaging',
                data: '{ pageId: "1",pageSize: "' + PageSize + '" }',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                beforeSend: function () {

                    $('#loader-wrapper').show();
                },
                success: function (result) {
                    $('#divDataContainer-Santionpost').empty();
                    $('#divDataContainer-Santionpost').append(result);
                },
                error: function (error) {
                    $('#divDataContainer-Santionpost').empty();
                    $('#divDataContainer-Santionpost').append(error.responseText);

                },
                complete: function (results) {

                    $('#loader-wrapper').hide();
                }
            });

        });


    });



</script>