SBL.eLegistrator.HouseController.Web/Areas/SuperAdmin/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Models
{
    public class EventViewModel
    {

        public int EventId { get; set; }

        [Required(ErrorMessage = "Event Name is Required")]
        [MaxLength(500, ErrorMessage = "Maximum 500 characters allowed")]
        public string EventName { get; set; }

        
        [MaxLength(500, ErrorMessage = "Maximum 500 characters allowed")]
        public string EventNameLocal { get; set; }

        [Required(ErrorMessage = " Name is Required")]
        public int? PaperCategoryTypeId { get; set; }

        public bool IsLOB { get; set; }

        public bool IsDepartment { get; set; }

        public bool IsCommittee { get; set; }

        public bool IsProceeding { get; set; }

        public bool IsMember { get; set; }
        [Required(ErrorMessage = "Order is Required")]
        public int? OrderingID { get; set; }

        public string PdfPath { get; set; }

        public DateTime? AddedDate { get; set; }

        public string ModifiedBy { get; set; }

        public DateTime? ModifiedWhen { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? CreatedWhen { get; set; }

        public bool Active { get; set; }

       
        public string RuleNo { get; set; }

        public string Mode { get; set; }

        public SelectList PaperCatTypes { get; set; }

      
        public string GetPapCatName { get; set; }

    }
}

SBL.eLegistrator.HouseController.Web/Areas/Admin/Controllers/EventController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
////using SBL.DomainModel.Models.AdminEvent;
//using SBL.eLegislator.HPMS.ServiceAdaptor;
//using SBL.Service.Common;
//using SBL.eLegistrator.HouseController.Web.Helpers;

//namespace SBL.eLegistrator.HouseController.Web.Areas.Admin.Controllers
//{
//    public class EventController : Controller
//    {
//        //
//        // GET: /Admin/Event/

//        //public ActionResult Index()
//        //{
//        //    return View();
//        //}

//        ServiceAdaptor serviceAdaptor = new ServiceAdaptor();
//        [HttpGet]
//        public ActionResult AddEvent()
//        {
//            mAEvent events = new mAEvent();
//            events.mode = "Insert";
//            return View(events);
//        }
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult AddEvent(mAEvent events)
//        {
//            if (events.mode == "Insert")
//            {
//                //ServiceParameter serviceparameter = ServiceParameter.Create("Events", "AddEvent", events);
//                //int result = Convert.ToInt32(serviceAdaptor.CallService(serviceparameter));
//                Helper.ExecuteService("AEvent", "AddEvent", events);
//                return RedirectToAction("GetEventList");
//            }
//            else if (events.mode == "Edit")
//            {
//                //ServiceParameter serviceparameter = ServiceParameter.Create("Events", "UpdateEvent", events);
//                //int result = Convert.ToInt32(serviceAdaptor.CallService(serviceparameter));
//                Helper.ExecuteService("AEvent", "UpdateEvent", events);
//                return RedirectToAction("GetEventList");
//            }
//            return null;
//        }
//        const int pageSize = 10;
//        //[HttpGet]
//        public ActionResult GetEventList(int PageNumber = 1, int LoopStart = 1, int LoopEnd = 5, string SearchText = "")
//        {
//            //ServiceParameter serviceParameter = ServiceParameter.Create("Events", "EventList", null);
//            List<mAEvent> events = (List<mAEvent>)(Helper.ExecuteService("AEvent", "EventList", null));

//            var model = new PagedList<mAEvent>()
//            {
//                //List = distrctList.ToList(),
//                List = events.Skip((PageNumber - 1) * pageSize).Take(pageSize).ToList(),
//                CurrentPage = PageNumber,
//                RowsPerPage = pageSize,
//                TotalRecordCount = events.Count(),
//                LoopEnd = LoopEnd,
//                LoopStart = LoopStart,
//                SearchText = SearchText
//            };
//            if (Request.IsAjaxRequest())
//            {
//                return PartialView("_Event", model);
//            }
//            return View(model);
//        }

//        public ActionResult EditEvent(int EventId)
//        {
//            //ServiceParameter serviceparameter = ServiceParameter.Create("Events", "EditEvent", EventId);
//            mAEvent events = (mAEvent)(Helper.ExecuteService("AEvent", "EditEvent", EventId));
//            events.mode = "Edit";
//            return View("AddEvent", events);
//        }
//        //[ValidateAntiForgeryToken]
//        public ActionResult DeleteEvent(int EventId)
//        {
//            //ServiceParameter serviceparameter = ServiceParameter.Create("Events", "DeleteEvent", EventId);
//            List<mAEvent> data = (List<mAEvent>)Helper.ExecuteService("AEvent", "DeleteEvent", EventId);
//            //return PartialView("EventList", data);
//            return RedirectToAction("GetEventList");
//        }

//    }
//}

SBL.eLegistrator.HouseController.Web/Areas/SuperAdmin/Controllers/EventController.cs
using Microsoft.Security.Application;
using SBL.eLegistrator.HouseController.Web.Extensions;

using SBL.DomainModel.Models.Event;
using SBL.eLegistrator.HouseController.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Extensions;
using SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Models;
using SBL.DomainModel.Models.PaperLaid;
using SBL.eLegistrator.HouseController.Filters;
using SBL.eLegistrator.HouseController.Web.Filters;
using SBL.eLegistrator.HouseController.Web.Utility;

namespace SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Controllers
{
    [Audit]
    [SBLAuthorize(Allow = "Authenticated")]
    [NoCache]
    public class EventController : Controller
    {
        //
        // GET: /SuperAdmin/Event/

        public ActionResult Index()
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                var Events = (List<mEvent>)Helper.ExecuteService("Events", "GetAllEventsList", null);
                var model = Events.ToViewModel();
                return View(model);
            }
            catch (Exception ex)
            {

                ViewBag.ErrorMessage = "There is a Error While Getting Event Details";
                return View("AdminErrorPage");
                throw ex;
            }
           
        }

        public ActionResult CreateEvent()
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                var PaperTypes = (List<mPaperCategoryType>)Helper.ExecuteService("Events", "GetAllPaperCatTypes", null);
                var model = new EventViewModel()
                {
                    PaperCatTypes = new SelectList(PaperTypes, "PaperCategoryTypeId", "Name"),
                    Mode = "Add",
                    Active = true
                };
                return View("CreateEvent", model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a Error While Creating Event Details";
                return View("AdminErrorPage");
                throw ex;
            }
          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveEvent(EventViewModel model )
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                if (ModelState.IsValid)
                {
                    var Events = model.ToDomainModel();
                    if (model.Mode == "Add")
                    {
                        Helper.ExecuteService("Events", "CreateEvents", Events);

                    }
                    else
                    {
                        Helper.ExecuteService("Events", "UpdateEvents", Events);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

                ViewBag.ErrorMessage = "There is a Error While Saving Event Details";
                return View("AdminErrorPage");
                throw ex;
            }
          
        }

        public ActionResult EditEvent(string Id)
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                var PaperTypes = (List<mPaperCategoryType>)Helper.ExecuteService("Events", "GetAllPaperCatTypes", null);
                //mEvent EventToEdit = (mEvent)Helper.ExecuteService("Events", "GetEventBasedOnId", new mEvent { EventId = Id });
                mEvent EventToEdit = (mEvent)Helper.ExecuteService("Events", "GetEventBasedOnId", new mEvent { EventId = Convert.ToInt32(EncryptionUtility.Decrypt(Id.ToString())) });
                
                var model = EventToEdit.ToViewModel1(PaperTypes, "Edit");
                return View("CreateEvent", model);
            }
            catch (Exception ex)
            {

                ViewBag.ErrorMessage = "There is a Error While Editing Event Details";
                return View("AdminErrorPage");
                throw ex;
            }
           

        }

        public ActionResult DeleteEvent(int Id)
        {
            try
            {
                if (string.IsNullOrEmpty(CurrentSession.UserName))
                {
                    return RedirectToAction("LoginUP", "Account", new { @area = "" });
                }
                mEvent eventToDelete = (mEvent)Helper.ExecuteService("Events", "GetEventBasedOnId", new mEvent { EventId = Id });
                Helper.ExecuteService("Events", "DeleteEvents", eventToDelete);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "There is a Error While Deleting Event Details";
                return View("AdminErrorPage");
                throw ex;
            }
          


        }

    }
}

SBL.eLegistrator.HouseController.Web/Areas/SuperAdmin/Views/Event/Index.cshtml
@model  IEnumerable<SBL.eLegistrator.HouseController.Web.Areas.SuperAdmin.Models.EventViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
    int count = 0;
}
@Html.Action("LeftNavigationMenu", "SuperAdmin")
<div class="main-content">
    @Html.Partial("_BreadcrumbsPartial")
    <!-- #section:basics/content.breadcrumbs -->
    <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
            try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="@Url.Action("Index", "Event")">@Resources.MasterDataDashboard.Home</a>
            </li>

            <li>
                <a href="@Url.Action("Index", "Event")">@Resources.MasterDataDashboard.Events</a>
            </li>
            <li class="active">@Resources.MasterDataDashboard.List</li>
        </ul>

       @* <div class="legAssm">
            <span class="label label-large label-pink arrowed-in-right arrowed">@Html.Raw(ViewBag.CurrentAssemblyName)</span>
            <span class="label label-large label-purple arrowed">@Html.Raw(ViewBag.CurrentSessionName)</span>
        </div>*@

    </div>

    <!-- /section:basics/content.breadcrumbs -->
    <div class="page-content">
        <!-- #section:settings.box -->


        <!-- /section:settings.box -->
        <div class="ace-settings-container" id="ace-settings-container" style="margin-right: 20px;">
            <button class="btn  btn-sm btn-info" onclick="javascript:window.location.href=' /SuperAdmin/Event/CreateEvent';">
                <i class="ace-icon fa fa-pencil-square-o bigger-150"></i>
                <span class="bigger-110">@Resources.MasterDataDashboard.New</span>
            </button>
        </div>
        <div class="page-header">
            <h1>@Resources.MasterDataDashboard.Events
                <small>
                    <i class="ace-icon fa fa-angle-double-right"></i>
                    @Resources.MasterDataDashboard.EventsList
                </small>
            </h1>
        </div>
        <div id="Menu">
            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="pass-table">


                        @if (Model != null)
                        {
                            if (Model.Count() > 0)
                            {       
                                
                          
                            <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-2" aria-describedby="sample-table-2_info">
                                <thead>
                                    <tr role="row">

                                        <th class="center sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="" onclick="javascript:window.location.href=' /SuperAdmin/Event/Index';">@Resources.MasterDataDashboard.SNo</th>
                                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">@Resources.MasterDataDashboard.PaperCategoryName</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">@Resources.MasterDataDashboard.EventName</th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">@Resources.MasterDataDashboard.EventName1</th>
                                        
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Pass Type: activate to sort column ascending">@Resources.MasterDataDashboard.Order</th>
                                        <th class="sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label=""></th>
                                    </tr>
                                </thead>
                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                    @foreach (var item in Model)
                                    {
                                        count = count + 1;  
                                        <tr>
                                            <td class="center">
                                                @count
                                            </td>
                                                <td style="width: 20%">@item.GetPapCatName</td>
                                            <td style="width: 30%">@item.EventName</td>
                                            <td style="width: 30%">@item.EventNameLocal</td>
                                         
                                            <td style="width: 10%">@item.OrderingID</td>
                                            <td class="center" style="width: 10%">
                                                <div class="hidden-sm hidden-xs action-buttons">

                                                    @*<a data-rel="tooltip" class="green tooltip-success" title="Edit"  href="@Url.Action("EditEvent", "Event", new { Id = item.EventId })">
                                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                    </a>*@
                                                    <a data-rel="tooltip" class="green tooltip-success" title="Edit"  href="@Url.Action("EditEvent", "Event", new { Id = SBL.eLegistrator.HouseController.Web.Extensions.EncryptionUtility.Encrypt(item.EventId.ToString()) })">
                                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                    </a>

                                                    <a data-rel="tooltip" class="red tooltip-error" title="Delete" id="DeleteLink"  href="@Url.Action("DeleteEvent", "Event", new { Id = item.EventId })">
                                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                    </a>
                                                </div>

                                                <div class="hidden-md hidden-lg">
                                                    <div class="inline position-relative">
                                                        <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                                            <i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
                                                        </button>

                                                        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">

                                                            <li>
                                                                <a  href="@Url.Action("EditEvent", "Event", new { Id = item.EventId })" class="tooltip-success" data-rel="tooltip" title="Edit">
                                                                    <span class="green">
                                                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                                    </span>
                                                                </a>

                                                            </li>

                                                            <li>
                                                                <a  href="@Url.Action("DeleteEvent", "Event", new { Id = item.EventId })"  class="tooltip-error" data-rel="tooltip" title="Delete">
                                                                    <span class="red">
                                                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                                    </span>
                                                                </a>

                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>                                                                
                                    }

                                </tbody>
                            </table>
                            <!-- PAGE CONTENT ENDS -->
                            }
                            else
                            {
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="alert alert-info">

                                        <strong>@Resources.MasterDataDashboard.NoEventRecordsFound</strong><br />


                                    </div>
                                </div>
                            </div>
                            }
                        }

                    </div>

                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
        </div>
        <!-- /.page-content -->
    </div>
    <!-- /.main-content -->

    <div class="footer">
        <div class="footer-inner">
            <!-- #section:basics/footer -->
            <div class="footer-content">
                @* <span class="bigger-100">
                    <span class="blue bolder">eVidhan@@@DateTime.Now.Year</span>
                </span>*@

            </div>

            <!-- /section:basics/footer -->
        </div>
    </div>

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div>

<div id="dialog-confirm" class="hide">
    <div id="DialogMessage" class="alert alert-info bigger-110">
        Are You Sure Want to Delete.
    </div>

    <div class="space-6"></div>
</div>
<div id="divDataContainer">
</div>

<script src="/assets/js/jquery.dataTables.min.js"></script>
<script src="/assets/js/jquery.dataTables.bootstrap.js"></script>
<script src="~/assets/js/bootbox.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $("#assemblymain").addClass("active open");
        $("#assemblysub").addClass("nav-show").css("display", "block");
        $("#eventlist").addClass("active");
        $("#assemblylinkid").removeClass("fa-comment").addClass("fa-comment-o");


    });

    jQuery(function ($) {
        var oTable1 =
        $('#sample-table-2')
        //.wrap("<div class='dataTables_borderWrap' />")   //if you are applying horizontal scrolling (sScrollX)
        .dataTable({
            bAutoWidth: true,
            "aLengthMenu": [[50, 100, 200, 400, -1], [50, 100, 200, 400, "All"]],
            "iDisplayLength": 50,
            "aoColumns": [
              { "bSortable": false },
              null, null,null,null,
              { "bSortable": false }
            ]

        });

        //oTable1.fnSort([[2, 'asc']]);

        $('[data-rel="tooltip"]').tooltip({ placement: tooltip_placement });
        function tooltip_placement(context, source) {
            var $source = $(source);
            var $parent = $source.closest('table')
            var off1 = $parent.offset();
            var w1 = $parent.width();

            var off2 = $source.offset();
            //var w2 = $source.width();

            if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2)) return 'right';
            return 'left';
        }

    })


    $(" #DeleteLink").on('click', function (e) {
        e.preventDefault();
        var url = $(this).attr('href');
        var message = "";
        var buttonlabel = "";
        var buttoncss = "";
        var title = "";
        if ($(this).attr('id') == "DeleteLink") {

            message = '@Resources.MasterDataDashboard.Areyousurewanttodelete';
            buttonlabel = '@Resources.MasterDataDashboard.Delete';
            buttoncss = "btn-danger";
            title = '@Resources.MasterDataDashboard.DeleteConfirmation'
        }

        bootbox.dialog({
            message: message,
            title: title,
            buttons: {
                success: {
                    label: buttonlabel,
                    className: buttoncss,
                    callback: function () {
                        window.location.href = url;
                    }
                },
                danger: {
                    label: '@Resources.MasterDataDashboard.Cancel',
                    className: "btn",
                    callback: function () {
                        $('.modal-dialog').modal('hide');
                    }
                },

            }
        });
    });
    
</script>